config/routes.rb
Rails.application.routes.draw do
  resources :scores
  resources :students
  get '/students/:id/edit_score' => 'students#edit_score'
  get '/main/login'
  post '/main/relay'
  post '/scores/relay' => 'scores#relay'
  #get '/students/:id/edit_score', to: 'students#edit_score', as: 'students'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/score.rb
class Score < ApplicationRecord
  belongs_to :student
end

app/models/student.rb
class Student < ApplicationRecord
	has_many :Score, dependent: :delete_all
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/main_controller.rb
class MainController < ApplicationController
	def login
		session[:authen] = false
	end

	def relay
		id = params[:userid]
		pass = params[:password]
		users = User.find(id)
		if(users.authenticate(pass))
			session[:userid] = id
			session[:authen] = true
			redirect_to :controller=>'students',:action=>'index'
		else
			redirect_to :controller=>'main',:action=>'login'
		end
	end

end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  before_action :set_score, only: %i[ show edit update destroy ]

  # GET /scores or /scores.json
  def index
    if(!session[:authen])
        redirect_to :controller=>'main',:action=>'login'
      end
    session[:bedit] = 1
    @scores = Score.all
  end

  # GET /scores/1 or /scores/1.json
  def show
    if(!session[:authen])
        redirect_to :controller=>'main',:action=>'login'
      end
    if(session[:bedit].to_i==0)
      @path = "/students/#{session[:id]}/edit_score"
    else
      @path = scores_path
    end
  end

  # GET /scores/new
  def new
    if(!session[:authen])
        redirect_to :controller=>'main',:action=>'login'
      end
    @score = Score.new
  end

  # GET /scores/1/edit
  def edit
    if(!session[:authen])
        redirect_to :controller=>'main',:action=>'login'
      end
    if(session[:bedit].to_i==0)
      @path = "/students/#{session[:id]}/edit_score"
    else
      @path = scores_path
    end
  end

  # POST /scores or /scores.json
  def create
    if(!session[:authen])
        redirect_to :controller=>'main',:action=>'login'
      end
    session[:bedit] = 1
    @score = Score.new(score_params)

    respond_to do |format|
      if @score.save
        format.html { redirect_to score_url(@score), notice: "Score was successfully created." }
        format.json { render :show, status: :created, location: @score }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scores/1 or /scores/1.json
  def update
    if(!session[:authen])
        redirect_to :controller=>'main',:action=>'login'
      end
    if(session[:bedit].to_i==0)
      @path = "/students/#{session[:id]}/edit_score"
    else
      @path = scores_path
    end

    respond_to do |format|
      if @score.update(score_params)
        format.html { redirect_to score_url(@score), notice: "Score was successfully updated." }
        format.json { render :show, status: :ok, location: @score }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scores/1 or /scores/1.json
  def destroy

    @score.destroy

    respond_to do |format|
      format.html { redirect_to scores_url, notice: "Score was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def relay
    if(!session[:authen])
        redirect_to :controller=>'main',:action=>'login'
      end
    commit = params[:commit]
    indexs = params[:index]
    if(commit == "Edit")
      redirect_to :controller=>'scores',:action=>'edit',:id=>indexs
    elsif (commit == "Delete")
      Score.find(indexs).destroy
      redirect_to :controller=>'students',:action=>'edit_score',:id=>indexs
    elsif (commit == "Add")
      redirect_to :controller=>'scores',:action=>'new'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_score
      @score = Score.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def score_params
      params.require(:score).permit(:student_id, :subject, :point, :grade)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: %i[ show edit update destroy ]

  # GET /students or /students.json
  def index
    @authen = session[:authen]
    @students = Student.all
  end

  # GET /students/1 or /students/1.json
  def show
      if(!session[:authen])
        redirect_to :controller=>'main',:action=>'login'
      end
  end

  # GET /students/new
  def new
    if(!session[:authen])
        redirect_to :controller=>'main',:action=>'login'
    end
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
    if(!session[:authen])
        redirect_to :controller=>'main',:action=>'login'
    end
  end

  # POST /students or /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to student_url(@student), notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to student_url(@student), notice: "Student was successfully updated." }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    @student.destroy

    respond_to do |format|
      format.html { redirect_to students_url, notice: "Student was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def edit_score
    @authen = session[:authen]
    session[:bedit] = 0
    session[:id] = params[:id]
    @id = params[:id]
    @score = Student.find(params[:id]).Score.all#.Score[0].id
    @av_score = 0
    @max_score = 0
    @max_subject
    @score.each do |n|
      @av_score = @av_score+n.point
      if(n.point > @max_score)
        @max_score=n.point
        @max_subject = n.subject
      end
    end
    @av_score = @av_score.to_f/@score.length.to_f
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.require(:student).permit(:name, :dob, :student_no, :class_year)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lect07</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/main/login.html.erb
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
<br>
<div class = "container">
<%= form_with url: '/main/relay', method: 'post', data: {turbo: false} do |form| %> 
	<%= form.label :userid, style: "display: block",class: "form-text" %>
    <%= form.text_field :userid,class: "form-control" %>
    <%= form.label :password, style: "display: block",class: "form-text" %>
    <%= form.password_field :password,class: "form-control" %><br>
    <%= form.submit text="Login",class: "btn btn-primary"%>
<%end%>
</div>

app/views/scores/_form.html.erb
<%= form_with(model: score) do |form| %>
  <% if score.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(score.errors.count, "error") %> prohibited this score from being saved:</h2>

      <ul>
        <% score.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <% if session[:bedit].to_i == 1%>
  <div>
    <%= form.label :student_id, style: "display: block" %>
    <%= form.text_field :student_id %>
  </div>
  <% end%>


  <div>
    <%= form.label :subject, style: "display: block" %>
    <%= form.text_field :subject %>
  </div>

  <div>
    <%= form.label :point, style: "display: block" %>
    <%= form.number_field :point %>
  </div>

  <div>
    <%= form.label :grade, style: "display: block" %>
    <%= form.text_field :grade %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/scores/_score.html.erb
<div id="<%= dom_id score %>">
  <p>
    <strong>Student:</strong>
    <%= score.student_id %>
  </p>

  <p>
    <strong>Subject:</strong>
    <%= score.subject %>
  </p>

  <p>
    <strong>Point:</strong>
    <%= score.point %>
  </p>

  <p>
    <strong>Grade:</strong>
    <%= score.grade %>
  </p>

</div>

app/views/scores/edit.html.erb
<h1>Editing score</h1>

<%= render "form", score: @score %>

<br>

<div>
  <%= link_to "Show this score", @score %> |
  <%= link_to "Back to scores", @path %>
</div>

app/views/scores/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Scores</h1>

<div id="scores">
  <% @scores.each do |score| %>
    <%= render score %>
    <p>
      <%= link_to "Show this score", score %>
    </p>
  <% end %>
</div>

<%= link_to "New score", new_score_path %>

app/views/scores/new.html.erb
<h1>New score</h1>

<%= render "form", score: @score %>

<br>

<div>
  <%= link_to "Back to scores", scores_path %>
</div>

app/views/scores/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @score %>

<div>
  <%= link_to "Edit this score", edit_score_path(@score) %> |
  <%= link_to "Back to scores", @path %>

  <%= button_to "Destroy this score", @score, method: :delete %>
</div>

app/views/students/_form.html.erb
<%= form_with(model: student) do |form| %>
  <% if student.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% student.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :dob, style: "display: block" %>
    <%= form.date_field :dob %>
  </div>

  <div>
    <%= form.label :student_no, style: "display: block" %>
    <%= form.text_field :student_no %>
  </div>

  <div>
    <%= form.label :class_year, style: "display: block" %>
    <%= form.number_field :class_year %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/students/_student.html.erb
<div id="<%= dom_id student %>">
  <p>
    <strong>Name:</strong>
    <%= student.name %>
  </p>

  <p>
    <strong>Dob:</strong>
    <%= student.dob %>
  </p>

  <p>
    <strong>Student no:</strong>
    <%= student.student_no %>
  </p>

  <p>
    <strong>Class year:</strong>
    <%= student.class_year %>
  </p>

</div>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Show this student", @student %> |
  <%= link_to "Back to students", students_path %>
</div>

app/views/students/edit_score.html.erb
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
<br>
<div class="container">
<%= "Average score you get is #{@av_score}" %> <br>
<%= "Your best subject is #{@max_subject}" %>
<% @score.each do |n|%> 
	<%= form_with url: '/scores/relay', method: 'post', data: {turbo: false} do |form| %> 
	<%= form.label :"You got #{n.point} which resulted in #{n.grade} in subject of #{n.subject}",class: "text-justify"%> 
	<%= form.hidden_field :index,value:n.id%> 
	<% if(@authen)%>
		<%= form.submit "Edit",class: "btn btn-info"%> 
		<%= form.submit "Delete",class: "btn btn-danger"%>
	<%end%>
<%end%> <%end%>
<% if(@authen)%>
<%= form_with url: '/scores/relay', method: 'post', data: {turbo: false} do |form| %> 
	<%= form.hidden_field :index,value:@id%> 
	<%= form.submit "Add",class: "btn btn-primary"%> 
<%end%>
<%end%>
</div>

app/views/students/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Students</h1>

<div id="students">
  <% @students.each do |student| %>
    <%= render student %>
    <p>
      <%= link_to "Show this student", student %>
    </p>
  <% end %>
</div>

<%= link_to "New student", new_student_path %>

app/views/students/new.html.erb
<h1>New student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Back to students", students_path %>
</div>

app/views/students/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @student %>

<div>
  <%= link_to "Edit this student", edit_student_path(@student) %> |
  <%= link_to "Back to students", students_path %>

  <%= button_to "Destroy this student", @student, method: :delete %>
</div>